name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 UTC every day
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set Git user
        run: |
          git config user.name "Mamun"
          git config user.email "skmamunislam786@gmail.com"

      - name: Generate content
        run: |
          echo "$(date): Automated update" >> activity_log.txt
          echo "{\"date\": \"$(date -I)\", \"timestamp\": $(date +%s), \"message\": \"Daily automated commit\"}" > daily_data.json
          if [ -f counter.txt ]; then
            count=$(cat counter.txt)
            echo $((count + 1)) > counter.txt
          else
            echo 1 > counter.txt
          fi

      - name: Commit changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit, creating empty commit"
            git commit --allow-empty -m "Daily update: $(date -I) [automated]"
          else
            git commit -m "Daily update: $(date -I) [automated]"
          fi
          git pull --rebase origin main
          git push origin main
