# .github/workflows/daily-commit.yml
name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 UTC every day
  workflow_dispatch: # Allows manual trigger
  
permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Generate content
      run: |
        # Create or update a log file with current date
        echo "$(date): Automated update" >> activity_log.txt
        
        # Create a simple data file
        echo "{\"date\": \"$(date -I)\", \"timestamp\": $(date +%s), \"message\": \"Daily automated commit\"}" > daily_data.json
        
        # Update a counter
        if [ -f counter.txt ]; then
          count=$(cat counter.txt)
          echo $((count + 1)) > counter.txt
        else
          echo 1 > counter.txt
        fi
        
    - name: Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'Daily automated update - $(date +%Y-%m-%d)'
        commit_options: '--no-verify --signoff'
        commit_user_name: github-actions[bot]
        commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
        commit_author: GitHub Actions <actions@github.com>
