name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 UTC every day
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
           token: ${{ secrets.GITHUB_TOKEN }}
           fetch-depth: 0
      - name: Set up Git user
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Generate content
        run: |
          # Create or update a log file with current date
          echo "$(date): Automated update" >> activity_log.txt
          
          # Create a simple data file
          echo "{\"date\": \"$(date -I)\", \"timestamp\": $(date +%s), \"message\": \"Daily automated commit\"}" > daily_data.json
          
          # Update a counter
          if [ -f counter.txt ]; then
            count=$(cat counter.txt)
            echo $((count + 1)) > counter.txt
          else
            echo 1 > counter.txt
          fi

      # ... previous steps
      - name: Set up Git identity
        run: |
         git config user.name "Mamun"
         git config user.email "skmamunislam786@gmail.com"

      - name: Commit changes
        run: |
         git add .
         if git diff --staged --quiet; then
          echo "No changes to commit, creating empty commit"
          git commit --allow-empty -m "Daily update: $(date -I) [automated]"
         else
           git commit -m "Daily update: $(date -I) [automated]"
         fi
         git pull --rebase origin main
         git push origin main
